#!/usr/bin/env python3
"""Install, back up, restore, and capture the explicit TBM Omarchy file manifest."""
import argparse
import datetime
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
TOKEN = '@@HOME@@'

def read_manifest():
    entries = json.loads((ROOT / 'manifest.json').read_text())
    for e in entries:
        safe_relative(e['path'])
    return entries

def safe_relative(value):
    p = Path(value)
    if p.is_absolute() or '..' in p.parts or not p.parts:
        raise ValueError('Unsafe relative path: ' + value)
    return p

def destination(home, rel):
    p = home / safe_relative(rel)
    # Never follow existing links outside or inside the target; changes must be explicit.
    for node in [p, *p.parents]:
        if node == home.parent:
            break
        if node.is_symlink():
            raise ValueError('Refusing symlink destination: ' + str(node))
    if p.exists() and not p.is_file():
        raise ValueError('Destination is not a regular file: ' + str(p))
    return p

def render(data, home):
    try:
        return data.decode().replace(TOKEN, str(home)).encode()
    except UnicodeDecodeError:
        return data

def monitors(value):
    if value is not None:
        names = value.split(',') if value else []
    else:
        try:
            result = subprocess.run(['hyprctl', 'monitors', '-j'], capture_output=True, text=True, check=True, timeout=5)
            names = [m['name'] for m in sorted(json.loads(result.stdout), key=lambda m: (not m.get('focused', False), m.get('x', 0)))]
        except (OSError, ValueError, subprocess.SubprocessError):
            names = []
    if len(names) != len(set(names)) or any(not re.fullmatch(r'[A-Za-z0-9_.:-]+', n) for n in names):
        raise ValueError('Monitor names must be unique connector names, separated by commas')
    return names

def machine_files(names):
    lines = ['-- Generated by TBM Omarchy; first monitor owns workspaces 1-5.']
    for index, name in enumerate(names):
        for slot in range(1, 6):
            lines.append('hl.workspace_rule({ workspace = "%s", monitor = %s, persistent = true })' % (index * 5 + slot, json.dumps(name)))
    monitor = ', monitor = ' + json.dumps(names[0]) if names else ''
    lines.append('o.window({ class = "^xfreerdp$", title = "^Windows VM - Omarchy$" }, { workspace = "2", maximize = true%s })' % monitor)
    return {
        '.config/hypr/tbm-machine.lua': ('\n'.join(lines) + '\n').encode(),
        '.config/omarchy/workspace-map.json': (json.dumps({n: i * 5 for i, n in enumerate(names)}) + '\n').encode(),
        '.config/omarchy/workspace-map.js': ('.pragma library\nvar offsets = ' + json.dumps({n: i * 5 for i, n in enumerate(names)}) + ';\n').encode(),
    }

def install(args):
    home = args.home.absolute()
    # Literal home paths appear in Lua, QML, shell, desktop entries, and services.
    # Fail before writing instead of incorrectly escaping unusual usernames/paths.
    if not re.fullmatch(r'/[A-Za-z0-9_./-]+', str(home)):
        raise ValueError('Install home path must contain only letters, digits, _, -, / and .')
    if args.apply and home == Path.home():
        if os.geteuid() == 0:
            raise ValueError('Run as your normal desktop user, not root')
        if not Path('/usr/share/omarchy/default/hypr/bootstrap.lua').is_file() or not (home / '.config/hypr/hyprland.lua').is_file():
            raise ValueError('This installer requires the Lua-based Omarchy desktop; see docs/versions.txt')
    entries = read_manifest()
    outputs = {}
    for e in entries:
        if e['group'] == 'voice-osd' and not args.with_osd:
            continue
        src = ROOT / 'home' / e['path']
        data = render(src.read_bytes(), home)
        if e['path'] == '.config/voxtype/config.toml' and args.with_osd:
            data = data.replace(b'[osd]\nenabled = true', b'[osd]\nenabled = false')
        outputs[e['path']] = (data, src.stat().st_mode & 0o777)
    if args.with_osd and not (home / '.local/share/voxtype/tbm-osd/voxtype-osd-gtk4-colors').is_file():
        raise ValueError('Build the custom OSD first: ./scripts/build-osd.sh')
    for rel, data in machine_files(monitors(args.monitors)).items():
        outputs[rel] = (data, 0o644)
    pending = []
    for rel, (data, mode) in outputs.items():
        target = destination(home, rel)
        if target.exists() and target.read_bytes() == data and target.stat().st_mode & 0o777 == mode:
            continue
        pending.append((rel, data, mode))
    print(('Applying' if args.apply else 'Preview:') + ' %d file changes' % len(pending))
    if not args.apply:
        for rel, _, _ in pending:
            print(rel)
        return
    if not pending:
        print('Already up to date.')
        return
    backup = home / '.local/state/tbm-omarchy/backups' / datetime.datetime.now().strftime('%Y%m%d-%H%M%S-%f')
    destination(home, str(backup.relative_to(home)) + '/receipt.json')
    backup.mkdir(parents=True, mode=0o700)
    receipt = {'version': 1, 'home': str(home), 'files': []}
    # Save every preimage and a complete receipt before the first mutation.
    for rel, data, mode in pending:
        target = home / rel
        existed = target.exists()
        if existed:
            old = backup / 'files' / rel
            old.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(target, old)
        receipt['files'].append({'path': rel, 'existed': existed, 'installed_sha256': hashlib.sha256(data).hexdigest()})
    (backup / 'receipt.json').write_text(json.dumps(receipt, indent=2) + '\n')
    for rel, data, mode in pending:
        target = destination(home, rel)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        target.chmod(mode)
    print('Backup:', backup)
    print('Run ./scripts/activate.sh from your Omarchy desktop when ready.')

def restore(args):
    backup = args.backup.absolute()
    receipt = json.loads((backup / 'receipt.json').read_text())
    home = Path(receipt['home'])
    entries = receipt['files']
    # Refuse to destroy any edits made after install unless explicitly requested.
    for e in entries:
        target = destination(home, e['path'])
        if not args.force and target.exists() and hashlib.sha256(target.read_bytes()).hexdigest() != e['installed_sha256']:
            raise ValueError('Changed since install; save edits or use --force: ' + str(target))
        if e['existed'] and not (backup / 'files' / safe_relative(e['path'])).is_file():
            raise ValueError('Missing backup for ' + e['path'])
    for e in entries:
        target = destination(home, e['path'])
        if e['existed']:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(backup / 'files' / e['path'], target)
        else:
            target.unlink(missing_ok=True)
    print('Restored', len(entries), 'files. Reload the desktop when ready.')

def capture(args):
    home = args.home.absolute()
    # Machine layout stays local; managed captures cannot accidentally collect credentials.
    skip = {'.config/hypr/monitors.lua', '.config/hypr/hyprland.lua', '.config/omarchy/plugins/tbm.workspaces/Workspaces.qml'}
    count = 0
    for e in read_manifest():
        if e['path'] in skip or e.get('capture') is False:
            continue
        src = destination(home, e['path'])
        if not src.exists():
            print('Missing (retained in repository):', e['path'])
            continue
        data = src.read_bytes()
        try:
            text = data.decode().replace(str(home), TOKEN)
            if e['path'] == '.config/voxtype/config.toml':
                text = text.replace('[osd]\nenabled = false', '[osd]\nenabled = true')
            data = text.encode()
        except UnicodeDecodeError:
            pass
        target = ROOT / 'home' / e['path']
        if target.read_bytes() != data:
            count += 1
            print(('Capture: ' if args.apply else 'Would capture: ') + e['path'])
            if args.apply:
                target.write_bytes(data)
                target.chmod(src.stat().st_mode & 0o777)
    print(count, 'changes. Review git diff before committing; capture never pushes.')

def doctor(args):
    required = ['omarchy', 'hyprctl', 'quickshell', 'python3', 'voxtype', 'wtype', 'wl-copy', 'notify-send', 'jq', 'socat']
    optional = ['microsoft-edge-stable', 'chatgpt', 'hermes', 'imv', 'cargo', 'meson']
    for cmd in required + optional:
        print(('OK      ' if shutil.which(cmd) else 'MISSING ') + cmd + (' (optional)' if cmd in optional else ''))
    print('Reference versions:'); print((ROOT / 'docs/versions.txt').read_text())
    print('Check ./docs/new-pc.md for model downloads, app sign-ins, services, and hardware setup.')

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest='command', required=True)
    for name in ('install', 'capture'):
        p = sub.add_parser(name)
        p.add_argument('--home', type=Path, default=Path.home())
        p.add_argument('--apply', action='store_true', help='write changes (default only previews)')
        if name == 'install':
            p.add_argument('--monitors', help='comma-separated connector names, primary first; otherwise detect')
            p.add_argument('--with-osd', action='store_true')
    p = sub.add_parser('restore'); p.add_argument('backup', type=Path); p.add_argument('--force', action='store_true')
    sub.add_parser('doctor')
    args = parser.parse_args()
    try:
        globals()[args.command](args)
    except (ValueError, OSError) as error:
        parser.exit(1, str(error) + '\n')

if __name__ == '__main__':
    main()
